### ISSUE TITLE
Make it possible to specify julia-path as a flag?

### ISSUE THREAD

**Issue by oxinabox** [fredrikekre/jlpkg#5]
I see from the readme, on needs to specify path to Julia executable at install time.

I would rather do it as a flag since I am using at least 3 installs of Julia at a time.
Which I have aliased to
`julia-1.0`, `julia-1.1` and `julia-master`.
And I often want to test on each of these in a different tab.

**Comment by fredrikekre** [comment]
So do I, but I have found that using the latest julia for jlpkg is sufficient -- it has the best Pkg manager. The only thing that is affected is essentially packages compat with Julia, i.e. VERSION, but I have not found this to be a problem.

You can also just use
```
$ alias julia="julia-master"
```
to change the behavior for different terminal sessions etc. Do you still think it is worth adding this? It is a bit more involved since we need to either examine this flag before running julia, or restarting julia from within the script itself.

**Comment by oxinabox** [comment]
Yes, because it seems I often want to test things that break on different Julia versions. (At least that is why I am testing them)

Like Cthulhu, Cassette, MagneticReadHead, etc.

Or even things that contains compat related branches.

I guess one of the main reasons I want to test from the command line is that I think it would be a better way too test multiple versions.

**Comment by fredrikekre** [comment]
@oxinabox, I think you saw my WIP commit where I was complaining about the extra time. I first thought that it might be because of the extra parsing time of arguments, but it's probably just that we have to pay for Julia startup-time twice.

**Comment by oxinabox** [comment]
yeah,  i would guess it is startup time twice. I haven't found it too bad.
